version: '3.8'

services:
  couch:
    container_name: CouchDB
    image: couchdb
    restart: unless-stopped
    networks:
      - compose-network
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - 5984:5984
    volumes:
      - couchdbvolume:/opt/couchdb/data
      
  mssql:
    container_name: MSSQL
    image: mcr.microsoft.com/azure-sql-edge
    restart: unless-stopped
    ports:
      - "1433:1433"
      - "1401:1401"
    volumes:
      - sqlvolume:/var/opt/mssql/data
    user: root
    environment:
      SA_PASSWORD: Fortuna2022!
      ACCEPT_EULA: Y
    networks:
      - compose-network
      
volumes:
  couchdbvolume:
    name: couchdbvolume
  sqlvolume:
    name: sqlvolume
  
networks:
  compose-network:
    driver: bridge